[package]
name = "effektio-core"
authors = [ "ben@effektio.org" ]
version = "0.1.0"
edition = "2021"
rust-version = "1.58"
description = "Core types and features of the effektio app"
homepage = "https://effekto.org"
repository = "https://github.com/effektio/effektio"
license-file = "../../LICENSE.txt"

[dependencies]
serde = "1.0.136"
serde_repr = "0.1"
csscolorparser = { version = "0.5.0", features = ["serde"] }
chrono = {version = "0.4", default-features = false, features = ["serde"]}
chrono-tz = { version = "0.5", default-features = false, features = ["serde"] }

[dependencies.matrix-sdk]
git = "https://github.com/matrix-org/matrix-rust-sdk/"
default-features = false

[dev-dependencies]
serde_json = "1.0.78"

[dev-dependencies.matrix-sdk]
git = "https://github.com/matrix-org/matrix-rust-sdk/"
features = ["rustls-tls"]
default-features = false