on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

name: Build Check

jobs:
  dart_analyze:
    name: dart analyze
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: subosito/flutter-action@v2
        with:
          channel: stable
      - working-directory: app
        run: dart analyze
      - working-directory: effektio_flutter_sdk
        run: dart analyze